### ISSUE TITLE
Reverse image doesn't fully search

### ISSUE THREAD

**Issue by whung1** [dxprog/reddit-booru#22] opened 2015-08-05 17:56 UTC
Reverse image search does not fully search all subreddits depending on subreddits ticked. If this is an intentional feature, would probably help to store temp cookies on Show NSFW and subreddit ticked options in order to help multiple image searches.

If those settings are saved, it might be an issue stemming with the chrome add-on overwriting existing cookies, as that is my way of usually searching for something.

**Comment by dxprog** [comment] 2015-08-06 00:35
There are several scenarios in play here (and, yes, it's highly confusing and even I'm not 100% of the specifics anymore):

- cookies for selected sources are set when you go to redditbooru.com and select something from the dropdown. These are the defaults used when you perform any subsequent kind of search from any location (within redditbooru or through the browser extension)
- cookies are _not_ set when you select a source from the drop down when you're in the middle of a search. The thinking here was that the user may only want to temporarily modify the current search they are currently performing.

The obvious issue here is that the same physical interface piece has its logic changed contextually but doesn't actually let the user know. The answer that I arrived to some time ago (but not actually implemented yet) is to have essentially a "modify search" pane/modal/whatever within the context of the search and the nav will go what it's supposed to do: modify things globally. Additionally, the "show posts from" menu is going to get a make over to make it more clear what it does in addition to polishing its behaviour.

I'm going to go ahead and use this ticket as a placeholder for the above functionality.

**Comment by whung1** [comment] 2015-08-07 02:32
I tested it and it seems like what you said is true.

There still remains a bug where unticking all subreddits pre-search will not store the cookie and display all subreddits' posts/search hits rather than none. Not sure why this edge case exists but maybe to prevent user stupidity. Its not extremely important but something to keep an eye out for in case you weren't aware.

**Comment by chiefnoah** [comment] 2015-08-07 02:55
That sounds more like the intended behavior of the API. If the request doesn't say which subs to search in, it defaults to all of them. Maybe an "All" checkbox that autochecks when none of the other boxes are checked to help inform the users that that is how it will behave?

**Comment by dxprog** [comment] 2015-08-07 15:20
Y'know, I've never actually bothered to see what happens when nothing is checked. I would have assumed that it would default to awwnime as I know there's _some_ logic in there for that. I'll evaluate that behaviour at the same time.

**Comment by dxprog** [comment] 2016-08-26 07:36
This behaviour is now [correctly documented](https://github.com/dxprog/reddit-booru/blob/master/api.md), so I'm closing this.

**Closed by dxprog** 2016-08-26 07:36 UTC
